spring:
  application:
    name: gateway-service

server:
  port: 8080
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true  
    service-url: 
      defaultZone: http://localhost:8761/eureka, http://localhost:8762/eureka

ribbon:
  eureka:
    enabled: true
    
zuul:
  routes:
    book-service:
      path: /book-service/**
      service-id: book-service
      strip-prefix: true
#      url: http://localhost:8081

    db-service:
      path: /db-service/**
      service-id: db-service
      strip-prefix: true
#      url: http://localhost:8082

    kafka-producer-service:
      path: /kafka-producer-service/**
      service-id: kafka-producer-service
      strip-prefix: true

