spring:
  application:
    name: book-service
    
server:
  port: 8081
#  servlet:
#    context-path: /book-service
    
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka, http://localhost:8762/eureka
  instance:
    instance-id: ${spring.application.name}:${random.int}
    
management:
  endpoints:
    web:
      exposure:
        include:
        - hystrix.stream
        - health
        
